CREATE TABLE IF NOT EXISTS USER(
ID BIGINT auto_increment PRIMARY KEY,
LOGIN VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
ROLE VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS BLOCKED_TOKEN(
ID VARCHAR(255) PRIMARY KEY);